### ISSUE TITLE
Is there a way to grab the results and store in Variable or print in console

### ISSUE THREAD

**Issue by chillz561** [pmaji/crypto-whale-watching-app#102]
I wanted to see if its possible in order to grab the results from the graphs and store them in a variable i can use to perform other tasks for example i want to get the prices and total btc that is in the orderbook that a whale has placed when i run dash it prints everything to the console but i would like to print the data from the app or store them in a variable any way of doing this?

**Comment by pmaji** [comment]
The answer is yes, but not directly from the app itself. This is probably best something you should do on your own out of a locally-run forked copy. 

It also depends on how much storage you have to dedicate to this, over what time horizon you'd like to do this, etc. Given that all of these are variable and up to your discretion, I'll just outline at a high level how I would go about doing it were I you. 

1 - start by picking a snapshot in time... a single timestamp once you have the app up and running locally. 
2 - take a snapshot (i.e. pause the refresh and make a hard copy of the order thickness at that point in time), thereafter filtering to only those actors you believe to be whales
3 - remember, the definition of what is a whale is something we set algorithmically, but you could change it manually on your end as well. 
4 - once you have this table and you have filtered it down to your whale observations, save this out in some manner (maybe a csv?) for your records
5 - functionalize steps 1-5 on some sort of regular interval to gather data over your range of interest.

I hope this works, and please do let me know if you end up doing something like this! If you write up a script that does what you want, please submit it and we'll add it to our codebase :) 

Appreciate your support of this project! Closing this out now.

**Comment by chillz561** [comment]
@pmaji thank you for the awesome project and fast response definitely will contribute if i can get it to work

**Comment by theimo1221** [comment]
@chillz561 as we store the data in pandas you could do whatever you want with that. I mean you could even erase all the graphical dash stuff and just log to a local file.
