### ISSUE TITLE
Code on Plotly 3.0 stops working

### ISSUE THREAD

**Issue by chopinvan** [pmaji/crypto-whale-watching-app#103]
Plotly 3.0 Changes some of its data presenting code. If anyone hits attribute append error, please check this thread. 

https://community.plot.ly/t/attributeerror-tuple-object-has-no-attribute-append/11782/4

**Comment by pmaji** [comment]
Thanks for posting this here @chopinvan. Going to close this for now but refer folks to this if it pops up again.
