### ISSUE TITLE
Websocket empty?

### ISSUE THREAD

**Issue by npucheta** [pmaji/crypto-whale-watching-app#109]
Hi all,
I have been trying out the app and I think is awesome, although I am getting a lot of websocket empty messages. This is the same issue that @pmaji open in https://github.com/danpaquin/coinbasepro-python/issues/361 but I think is specific to whale-watching-app hence I open it here. Taking a look at the code I think the problem is although the code is trying to use websockets, is still performing polling requests (for each websocket message) which are rate limited by CB. The line 25 in gdax_book is doing this:
            res = self._client.get_product_order_book(self.product,level=3)

for each message that is received on the websocket.
[CB docs mention this:
](https://docs.pro.coinbase.com/#get-product-order-book)Level 3 is only recommended for users wishing to maintain a full real-time order book using the websocket stream. Abuse of Level 3 via polling will cause your access to be limited or blocked.

At the moment I only see one way of fixing this:
-Get the full order book ONCE (when app is launched) and store in database
-update it for each message we get on the websocket

Let me know your thoughts please, happy to help with the project. 
Cheers

**Comment by npucheta** [comment]
My bad, I just realised that the get_product_order_book is only called after the if:
        if self._sequence == -1:
I removed that line as part of my troubleshooting and forgot to put it back, I will continue troubleshooting the issue though and see if I can find out the root cause. Cheers

**Comment by pmaji** [comment]
I hopped on over to the other thread you mentioned @npucheta. I see the transition from level 3 to level 2 and the custom rapper that seems to fix it, but I'm hesitant about integrating a wholesale change of that sort that isn't yet integrated into the package. I'll be following the thread to see how it evolves. In the meantime, if you try out the fix in your branch and think it works perfectly, feel free to submit a PR for review.
