### ISSUE TITLE
error help

### ISSUE THREAD

**Issue by zero03317** [pmaji/crypto-whale-watching-app#113]
error message below:
File "C:\Users\test\Downloads\crypto-whale-watching-app-master\crypto-whale-watching-app-master\gdax_book.py", line 23, in on_message
    sequence = message['sequence']
KeyError: 'sequence'

can help?

**Comment by pmaji** [comment]
Hi @zero03317 that is pretty generic and tough to trouble-shoot I'm afraid. Here are the steps I would recommend:

- create a new, fresh virtual environment (using conda, etc.)
- re-clone this repo fresh, and activate the aforementioned virtual environment
- install the needed packages using the requirements.txt in this repo
- re-try running the app.py with the version of python in your virutalenv
- give it around 30sec - 1.5 min (depending on computer) to warm up the websockets, and it should run

If not, it is something machine-specific that is difficult to trouble-shoot further on my end. Hope that helps!
