### ISSUE TITLE
Continuous improvement of documentation

### ISSUE THREAD

**Issue by pmaji** [pmaji/crypto-whale-watching-app#46]
- [x] update requirements.txt with few new packages added by contributors
- [x] figure out what kind of license we want to use for this project and add it to files / potentially read me
- [x] update README 
- [x] finalize comments throughout

**Comment by pmaji** [comment]
@theimo1221 FYI I added the comment "explanatory comment here to come" in a handful of places in the newest version of the app code that I just merged to Master. I went through and commented most of the sections that weren't explained, deleted some inactive code, etc. If you just command/find for "explanatory comment here to come" you'll see the few places where I could still use one sentence or so from you about the process.

**Comment by theimo1221** [comment]
Will take a look into it

**Comment by theimo1221** [comment]
I know recent change is not good commented, but it was a quite some code and a lot of changes due to limitations by plotly (e.g. no tooltip on lines)

**Comment by pmaji** [comment]
No worries @theimo1221 . My goals right now are as follows:
- Make sure that this new update finally kills @CrackLord 's hosting refresh problem.
- Update all documentation (primarily the README) to reflect the new horizontal + vertical whale detection methodology -- this is something I'll work on tonight. 
- Update all comments so that the entire codebase is well understood. (this is something we can do on and off over the next few days. We'll get to it whenever, but it is one of the next priorities.

**Comment by theimo1221** [comment]
You should consider putting link to top of readme.

**Comment by pmaji** [comment]
A link to what exactly @theimo1221 ? The website for @CrackLord is already linked in the readme, but I didn't want to add it as the website (top of the github page) until the refresh is consistent.

**Comment by pmaji** [comment]
Readme now updated with major edits. @theimo1221 feel free to give it a read whenever. I think it's now super clear.

**Comment by theimo1221** [comment]
#59 opens possibilities to improve this one by giving possibilitie to maybe add the content of readme via a spoiler.

**Comment by pmaji** [comment]
Good deal. Presently I view priorities of this issue as being:
- thorough commenting of present code as it exists
- updated readme to reflect recent small changes we made to drop tooltip, etc. (I'll knock this one out soon)
- spoiler readme option

**Comment by pmaji** [comment]
Alrighty. Took care of the licensing question which was the only outstanding hard-cutoff to-do in this thread. The other issue is one of continuous documentation (i.e. constantly commenting thoroughly so that everyone can understand what's going on). We still have a bit more work to do on that, but that is also a constant issue that will persist as long as the project is active, so it makes sense to closet this for now.
