### ISSUE TITLE
Variable controls for ladder price-point whales

### ISSUE THREAD

**Issue by pmaji** [pmaji/crypto-whale-watching-app#50]
@theimo1221 you can see in my updated README that I have split our definition of whale into two types. There is a bit of a methodological blind spot that I identified though when it comes to what I called "ladder price-point whales", i.e. those that we mark with the linebar chart instead of the bubble. Namely, the problem is that we ALSO pick up on psychological modal points. 

What I mean by this is that, for example, 10 ETH is a very popular volume amount. So is 5 ETH. If many people put orders for 10 ETH along the span of say pricepoints of $950 to $1000, our present methodology would flag this as a potential whale. That said, if we saw a bunch of orders for 10.0085 ETH spanning that same range of prices, THAT is more likely to be a whale, because it is a rarer volume number (and thus less likely to just be a psychological modal point that many people might pick).

It's very hard to control for this, but I think one way to do it might be to exclude from our ladder price-point whale-identification logic any span of orders that is obviously a popular order number (i.e. 10 / 5 / 1 / and maybe a few others). The problem is that this logic is a lot more based on assumptions than the single price-point whale identification logic, but we can make it a bit better I think (given the logic I laid out here). Let me know your thoughts.

**Comment by ac8493a** [comment]
Glad to see the implimintation of behavior economics. It would also be interesting to consider cultural variables especially those involving numbers.

**Comment by theimo1221** [comment]
`vol_grp_ask = vol_grp_ask[
        ((vol_grp_ask[TBL_VOLUME] >= minVolume) & (vol_grp_ask['count'] >= 2.0) & (vol_grp_ask['count'] < 70.0))]`

As you can see we already filter out those ladders existing with more than 70 orders.

In my opinion it´s up to the user to decide human behaviuor or whale.
Besides this would mean different levels for each pair.

**Comment by pmaji** [comment]
Yep @theimo1221 I am aware, but the question is about how arbitrarily that cutoff is being created.

I don't know if this is presently the best way of doing the filtering. A whale may very well set more than 70 orders via a ladder but not use a standard modal point, whereas other 70+ order volume types may be entirely innocuous. This is one of the hardest behavioral economic components of this project, because it is mostly guesstimation. My hunch is that we are better off filtering out specific obvious volume values that are DEFINITELY psychological modal points (like 10 ETH, etc.). But I need to give this more thought. For now I'm keeping this issue open because I'm not happy with it yet I think we can do this in a more robust manner.

**Comment by pmaji** [comment]
Just finished a call with @theimo1221 that included discussion of the 70+ order volume filter. Given distributional tests, it appears to be robust. Will include a brief explanation of this in the README in the future, and do additional stress-testing soon to confirm that this holds true under stress scenarios.
