### ISSUE TITLE
Questions to explore further beyond the app

### ISSUE THREAD

**Issue by pmaji** [pmaji/crypto-whale-watching-app#51]
Given the treasure trove of data that we now are developing, as well the growing community of traders / coders that are involved in this project, I wanted to open an issue where people can periodically contribute questions that they want explored further.

My aim to open up a Python Notebook separate from this app in which we can dig into deeper (perhaps more long-form analytic questions) that this app or curiosity in general may create. Comment below with any hypotheses you want tested or theories you want explored, etc., and I will add them to the master list of topics to add to the exploratory Python Notebook that will be created.

**List of subjects to investigate:**

- [ ] Investigate temporal weekly trends (i.e. what really are GDAX's volume / volatility trends over the course of a week, and are these patterns predictable? Do things really go up Sat. night and come down Sunday morning?) 
- [ ] Impact of holidays (if any) on trading patterns
- [ ] Is there a time-zone that dominates the volume?
- [ ] Are particularly time-zones more / less bearish / bullish than others?
- [ ] Is it true that eth price follows btc with a short but perceptible lag?
- [ ] Correlation between bot activity and price movement (i.e when bot trading is more prominent does that necessarily lead to a higher likelihood of upwards vs. downwards price swings)
- [ ] Correlation between more volume and price?
- [ ] Investigation of whether or not TA beats buy-and-hold and over what time span if at all?
- [ ] Portfolio performance question? Does holding the 20 lowest price coins vs. the 20 highest price coins yield a higher return over time? 
- [ ] Are there any exchanges in particular that more often than not lead the market? (i.e. does an upswing on GDAX cause an upswing elsewhere?)
- [ ] Look in the data to first identify what seem like the same bot trading regularly, and then see what correlation there is to price swings.

**Comment by anotherspacesong** [comment]
Correlation between price and volume, i.e. is higher volume during moves higher indicative of further strength

**Comment by HBlaskowski** [comment]
A popular topic here: Over a multi-year period, can Technical Analysis -- looking for patterns on graphs -- beat a buy and hold strategy?   There are many of these patterns that people swear by: "head and shoulders", "dead cat bounce", etc.   How would these have fared over the last three years?

**Comment by pmaji** [comment]
Thanks @anotherspacesong; I've integrated your question into the master list.

**Comment by pmaji** [comment]
@HBlaskowski oooo that's going to be a tough / fun one, given how... murky definitions of various TA strategies are haha. Excited to see how we can operationalize this one. 

I've added it to the list.

**Comment by pmaji** [comment]
We've got a good list to start with here, and given that the response rate has died down, I'm closing the issue. Hope to get started on some of these shortly.

**Comment by theimo1221** [comment]
@pmaji Please open up an issue for each element or keep this one open.

To be honest I hadn´t it on my radar....

**Comment by pmaji** [comment]
I'm totally fine with keeping it open. I don't think I have the time to get to this super soon, but I will begin work on these questions in the mid-term. I think my plan is to open a separate repo to host the python code and jupyter notebooks, but I haven't decided yet. Happy to take feedback on that. Excited by a few of these questions for sure. Re-opening at your request @theimo1221  :)

**Comment by pmaji** [comment]
So I got around recently to answering one of these questions about the impact of temporality / seasonality on price. [You can check out that preliminary analysis here.](https://github.com/pmaji/data-science-toolkit/blob/master/time-series/forecasting_with_prophet.ipynb) In an attempt to keep this repo devoted only to the app itself and not exogenous research items, I will likewise tackle the rest of them as I have time [in the same data science research repository,](https://github.com/pmaji/data-science-toolkit) so follow that for more info! Closing this out for now.
