### ISSUE TITLE
Problem with "unique" orders

### ISSUE THREAD

**Issue by theimo1221** [pmaji/crypto-whale-watching-app#54]
Look at this comparision:
![image](https://user-images.githubusercontent.com/20605452/36438891-822cb9c2-166b-11e8-99a4-fcb181c61892.png)

In the bottom current code, wich groups by price and then filters all less than 1% of Volume in Range.
In the top I first filter all orders < 1% of Volume in Range and then group by prize.

This results in much better data. e.g. the sell order at 0.083 (yellow) is 1 50 ETH order plus 5 additional orders (summed up to 6 ETH).
Top graph warns about a whale. Bottom graph say "Nah, it´s okay, there are 6 unique orders"

Wrote it as an issue to post picture.

**Comment by pmaji** [comment]
Closing this because I merged the PR that fixed the filter order problem that lead to this. Great catch @theimo1221 .
