### ISSUE TITLE
building issues

### ISSUE THREAD

**Issue by chris56a** [pmaji/crypto-whale-watching-app#56]
am i the only one not able to build this?? downloaded dash and still can't find out how to build this at all?

**Comment by theimo1221** [comment]
Only thing you need to install is python 3.6 and then run
`pip install -r /path/to/requirements.txt`
in command line.

Once its finished type

`python app.py`

Then open up broswer and go to [127.0.0.1:8050](http://127.0.0.1:8050)

**Comment by chris56a** [comment]
python: can't open file 'app.py': [Errno 2] No such file or directory
Chriss-MacBook-Pro:~ chrismurphy$ python /Users/chrismurphy/Desktop/app.py 
  File "/Users/chrismurphy/Desktop/app.py", line 27
SyntaxError: Non-ASCII character '\xe2' in file /Users/chrismurphy/Desktop/app.py on line 27, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
Chriss-MacBook-Pro:~ chrismurphy$

**Comment by theimo1221** [comment]
As far as I know that's a python 2 error 
You need 3.6 for this

**Comment by pmaji** [comment]
Correct @theimo1221 ; @chris56a  this looks like a python version issue. Update your python version, use pip3 for your installs, and then try again; that should fix it.

**Comment by theimo1221** [comment]
Vote4Close

**Comment by pmaji** [comment]
@chris56a let me know if you are having more trouble. I assume you figured it out by now, so I'm closing this one. Definitely a Python issue though, not a problem with the app code.
