### ISSUE TITLE
License

### ISSUE THREAD

**Issue by anandanand84** [pmaji/crypto-whale-watching-app#63]
Is this open source and what is the license?

**Comment by theimo1221** [comment]
At the moment this is open source and free of charge 

But we are happy about some donation to get it hosted on an own domain 

So you can either use link in read me or run it locally

**Comment by pmaji** [comment]
Entirely correct @anandanand84. I'll look into posting an actual license but for now we are entirely open source, no cost, and just hoping folks will donate (haven't gotten much yet) for permanent hosting. Thanks for asking, but closing this thread now.
