### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by PeanutPete** [pmaji/crypto-whale-watching-app#67]
Hi, 

I really appreciate this tool and it's fantastic. The only thing really bugs me is that the tool tips when you hover over an order block disappears too fast without you getting a chance to digest the information. Is there any way you could possibly make an option to just always keep the hover tooltips on if for example you clicked the order block.

Thanks

**Comment by mifunetoshiro** [comment]
It closes because the data refreshes. Click on "Freeze all" to temporarily stop it refreshing.

**Comment by PeanutPete** [comment]
Ah cool, thanks, probs should have figured that out by myself :) Cheers.
