### ISSUE TITLE
Adding "total price" worth to ladder whale orders

### ISSUE THREAD

**Issue by mifunetoshiro** [pmaji/crypto-whale-watching-app#68]
Now with #66 merged, hovering over a bubble shows the total price of the order/s. I tried to add the same to the ladder whale orders, and if I play with a simple test dataframe it works, but when I try with app.py, I get an error on:
```
    vol_grp_bid = vol_grp_bid[
        ((vol_grp_bid[TBL_VOLUME] >= minVolume) & (vol_grp_bid['count'] >= 2.0) & (vol_grp_bid['count'] < 70.0))]
```
for some reason. Could someone with more experience implement this?

**Comment by theimo1221** [comment]
Wich Error and are you sure it´s on that line and not cause error in line before?

**Comment by mifunetoshiro** [comment]
This error, see the code I tried: https://github.com/mifunetoshiro/crypto-whale-watching-app/commit/7647a92842f3fb27464d355cf4b6e0dc4a6cbc42

> Exception in thread Thread-57:
> Traceback (most recent call last):
>   File "C:\Python\lib\site-packages\pandas\core\indexes\base.py", line 2525, in get_loc
>     return self._engine.get_loc(key)
>   File "pandas\_libs\index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas\_libs\index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas\_libs\hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
>   File "pandas\_libs\hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
> KeyError: 'volume'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Python\lib\threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "C:\Python\lib\threading.py", line 864, in run
>     self._target(*self._args, **self._kwargs)
>   File "C:\Users\Uporabnik\Desktop\app.py", line 596, in recalcThread
>     count = count+1 if (not calc_data(pair)) else 0
>   File "C:\Users\Uporabnik\Desktop\app.py", line 223, in calc_data
>     ((vol_grp_bid[TBL_VOLUME] >= minVolume) & (vol_grp_bid['count'] >= 2.0) & (vol_grp_bid['count'] < 70.0))]
>   File "C:\Python\lib\site-packages\pandas\core\frame.py", line 2139, in __getitem__
>     return self._getitem_column(key)
>   File "C:\Python\lib\site-packages\pandas\core\frame.py", line 2151, in _getitem_column
>     result = result[key]
>   File "C:\Python\lib\site-packages\pandas\core\frame.py", line 2139, in __getitem__
>     return self._getitem_column(key)
>   File "C:\Python\lib\site-packages\pandas\core\frame.py", line 2146, in _getitem_column
>     return self._get_item_cache(key)
>   File "C:\Python\lib\site-packages\pandas\core\generic.py", line 1842, in _get_item_cache
>     values = self._data.get(item)
>   File "C:\Python\lib\site-packages\pandas\core\internals.py", line 3843, in get
>     loc = self.items.get_loc(item)
>   File "C:\Python\lib\site-packages\pandas\core\indexes\base.py", line 2527, in get_loc
>     return self._engine.get_loc(self._maybe_cast_indexer(key))
>   File "pandas\_libs\index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas\_libs\index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas\_libs\hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
>   File "pandas\_libs\hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
> KeyError: 'volume'

**Comment by mifunetoshiro** [comment]
Ah, I see: `rename(columns={'amin': 'min_Price', 'amax': 'max_Price', 'sum': 'volume', 'sum': 'total_price'})`

This renames both sum columns to 'total_price' instead of 'volume' and 'total_price'. So how do you rename two sums to two different names?

**Comment by theimo1221** [comment]
`vol_grp_ask = ask_tbl.groupby([TBL_VOLUME]).agg({TBL_PRICE: [np.min, np.max, 'count'], TBL_VOLUME:{TBL_VOLUME:np.sum}, 'total_price': {'total_price':np.sum}).rename(columns={'amin': 'min_Price', 'amax': 'max_Price'})`

Is what you need I guess

**Comment by mifunetoshiro** [comment]
Ok, I figured it out. Instead of using the rename function, I manually renamed the columns with `vol_grp_bid.columns`. This is also unneeded after: `vol_grp_bid.columns.droplevel(0)`

Will add pull request soon.

**Comment by theimo1221** [comment]
@mifunetoshiro Dropplevel (0) removes the groubby name  marked in following example:
![image](https://user-images.githubusercontent.com/20605452/36642603-20aad6ae-1a42-11e8-9d08-d7cac0c704a0.png)

**Comment by mifunetoshiro** [comment]
Yes, but in this way that I did it:

```
    vol_grp_bid = bid_tbl.groupby([TBL_VOLUME]).agg({TBL_PRICE: [np.min, np.max, 'count'], TBL_VOLUME: np.sum, 'total_price': np.sum})
    vol_grp_bid.columns = ['min_Price', 'max_Price', 'count', 'volume', 'total_price']
    vol_grp_ask = ask_tbl.groupby([TBL_VOLUME]).agg({TBL_PRICE: [np.min, np.max, 'count'], TBL_VOLUME: np.sum, 'total_price': np.sum})
    vol_grp_ask.columns = ['min_Price', 'max_Price', 'count', 'volume', 'total_price']
```

It's not needed, because there aren't 2 levels, and you get an error: 

> AttributeError: 'Index' object has no attribute 'droplevel'

**Comment by theimo1221** [comment]
ah okay, gotcha.
