### ISSUE TITLE
Exceptions in thread

### ISSUE THREAD

**Issue by mifunetoshiro** [pmaji/crypto-whale-watching-app#71]
Is it just me?

> Server should be running now
> Initializing order Book websocket for ETH-USD
> -- Subscribed! --
> 
> Initializing order Book websocket for ETH-BTC
> -- Subscribed! --
> 
> Initializing order Book websocket for BTC-USD
> -- Subscribed! --
> 
> Initializing order Book websocket for LTC-USD
> -- Subscribed! --
> 
> Initializing order Book websocket for LTC-BTC
> -- Subscribed! --
> 
> Initializing order Book websocket for ETH-EUR
> -- Subscribed! --
> 
> Initializing order Book websocket for BTC-EUR
> -- Subscribed! --
> 
> Initializing order Book websocket for LTC-EUR
> -- Subscribed! --
> 
> Initializing order Book websocket for BCH-USD
> -- Subscribed! --
> 
> Initializing order Book websocket for BCH-BTC
> -- Subscribed! --
> 
> Initializing order Book websocket for BCH-EUR
> -- Subscribed! --
> 
> Web sockets up
> Exception in thread Thread-2:
> Traceback (most recent call last):
>   File "C:\Python\lib\threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "C:\Python\lib\threading.py", line 864, in run
>     self._target(*self._args, **self._kwargs)
>   File "C:\Users\mifune\Desktop\app.py", line 592, in sendPrepareThread
>     sendCache = prepare_send()
>   File "C:\Users\mifune\Desktop\app.py", line 471, in prepare_send
>     figure=cData[exchange + ticker]
> KeyError: 'GDAXETH-USD'
> 
> ReCalc up
> Everything should be running now, starting Watchdog, to control the herd
> Watchdog detected dead Preparer, restarting
> Watchdog got some bad sheeps back to group
> Exception in thread Thread-47:
> Traceback (most recent call last):
>   File "C:\Python\lib\threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "C:\Python\lib\threading.py", line 864, in run
>     self._target(*self._args, **self._kwargs)
>   File "C:\Users\mifune\Desktop\app.py", line 592, in sendPrepareThread
>     sendCache = prepare_send()
>   File "C:\Users\mifune\Desktop\app.py", line 471, in prepare_send
>     figure=cData[exchange + ticker]
> KeyError: 'GDAXLTC-EUR'
>

**Comment by theimo1221** [comment]
No worries man, it´s on purpose  😃 
Give it 1-2 min to set up correctly, currently 35 Threads are running.

Initiating the Websocket and stuff has some problems especially from gdax side, so the watchdog is doing his job in restarting some threads to ensure all running correct.

I even actively perform an error in one thread from an other thread when it doesn´t recieves data from websocket, wich doesn´t cause the thread to stop, to let watchdog restarting it 😜 

So here is some tricky stuff, but if you let it run for 2-3 min all should be fine

**Comment by mifunetoshiro** [comment]
Ah, I see, interesting, thanks.
