### ISSUE TITLE
pair.webSocketKill division by zero error

### ISSUE THREAD

**Issue by mifunetoshiro** [pmaji/crypto-whale-watching-app#86]
```
Exception in thread Thread-66:
Traceback (most recent call last):
  File "C:\Python\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Python\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\mifune\Desktop\app.py", line 647, in websockThread
    kill = 5 / pair.webSocketKill
ZeroDivisionError: division by zero

```

**Comment by theimo1221** [comment]
@mifunetoshiro 
The variable is called "webSocketKill" it is intended to throw an error to crash the websocket thread.

To quote myself from #71:

> I even actively perform an error in one thread from an other thread when it doesn´t recieves data from websocket, wich doesn´t cause the thread to stop, to let watchdog restarting it 😜

**Comment by mifunetoshiro** [comment]
Ah, this is the error you were referring to. Got it :)
