### ISSUE TITLE
BTC-GBP plot is messed up

### ISSUE THREAD

**Issue by mifunetoshiro** [pmaji/crypto-whale-watching-app#89]
See horizontal line & annotation: https://i.imgur.com/UQ6qyS2.png

**Comment by mifunetoshiro** [comment]
LTC-BTC as well, but is less noticeable.

**Comment by theimo1221** [comment]
![image](https://user-images.githubusercontent.com/20605452/36933464-4f124874-1ed9-11e8-9ab4-e4588181b9eb.png)

**Comment by theimo1221** [comment]
![image](https://user-images.githubusercontent.com/20605452/36933589-070e2392-1edc-11e8-9a00-14bf88a07d90.png)
Spotted error.
If there is no Ladder on one of those sides he has a problem 😆

**Comment by theimo1221** [comment]
@mifunetoshiro I´m in final testing will post fix soon, nice bug detection from you 👍

**Comment by theimo1221** [comment]
![image](https://user-images.githubusercontent.com/20605452/36933788-5718ae54-1edf-11e8-9d2c-290300bbb6e2.png)
This is another error, due to rounding to 3 significant

**Comment by theimo1221** [comment]
@mifunetoshiro please test and review #90 for me it´s working

**Comment by mifunetoshiro** [comment]
Yes, it's ok now, thanks
