### ISSUE TITLE
*-BTC pairs should be 5 decimals not 4

### ISSUE THREAD

**Issue by mifunetoshiro** [pmaji/crypto-whale-watching-app#92]
E.g. ETH-BTC: 0.07564 BTC not 0.0756.

**Comment by theimo1221** [comment]
It's just one parameter at the top.
So feel free to change and commit it:wink:

**Comment by mifunetoshiro** [comment]
I tried, but it say e.g. 0.076 at the moment, and if I check whales.cracklord.com old version, it says 0.07588 market price...

**Comment by theimo1221** [comment]
You did it like I changed it here?

**Comment by mifunetoshiro** [comment]
Yes. I noticed this when comparing with cracklord.com's old version. There was a green buy bubble on the current version at market price, but on cracklord.com's version it was a red sell, because it was one decimal above market...

**Comment by pmaji** [comment]
Change made. Should be taken care of.
