### ISSUE TITLE
noob issue, invalid syntax

### ISSUE THREAD

**Issue by shawn-j** [pmaji/crypto-whale-watching-app#97]
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32

    pip install -r D:\_installers\crypto-whale-watching-app-master\requirements.txt
              ^
    SyntaxError: invalid syntax

**Comment by theimo1221** [comment]
@shawn-j  You have to run it inside CMD (Command Line) not inside Python

So don´t run
`python`
`pip install -r D:\_installers\crypto-whale-watching-app-master\requirements.txt`

Just run 
`pip install -r D:\_installers\crypto-whale-watching-app-master\requirements.txt`

**Comment by shawn-j** [comment]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\dma>pip install -r D:\_installers\crypto-whale-watching-app-master\requ
irements.txt
'pip' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\dma>


D:\_installers\crypto-whale-watching-app-master>pip install -r D:\_installers\cr
ypto-whale-watching-app-master\requirements.txt
'pip' is not recognized as an internal or external command,
operable program or batch file.

**Comment by theimo1221** [comment]
You miss a \ after d:
And missing pip can be because of wrong environmental variable

**Comment by theimo1221** [comment]
You miss a \ after d:
And missing pip can be because of wrong environmental variable

**Comment by shawn-j** [comment]
i searched and couldn't find pip.exe anywhere in my computer.. sorry if i'm having noob issues..  what do i type into google to find the solution?

**Comment by theimo1221** [comment]
@shawn-j 
First result in Google if you type:
`'pip' is not recognized as an internal or external command,
operable program or batch file.`

https://stackoverflow.com/questions/23708898/pip-is-not-recognized-as-an-internal-or-external-command

**Comment by theimo1221** [comment]
@shawn-j does it work?

**Comment by shawn-j** [comment]
just tried it, it didn't work:

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\dma>echo %PATH%
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Wi
ndows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Pr
ogram Files (x86)\Bitvise SSH Client;C:\Program Files\PuTTY\;C:\Program Files (x
86)\Brackets\command;C:\Program Files\Git\cmd;C:\Program Files (x86)\Gpg4win\..\
GnuPG\bin;C:\Users\dma\AppData\Local\GitHubDesktop\bin;%DASHLANE_DLL_DIR%

C:\Users\dma>setx PATH "%PATH%;C:\Python34\Scripts"

SUCCESS: Specified value was saved.

C:\Users\dma>pip install -r D:\_installers\crypto-whale-watching-app-master\requ
irements.txt
'pip' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\dma>

**Comment by theimo1221** [comment]
@shawn-j
This only works if python is installed to the folder wich you typed after path...
And due to the fact you wrote python34 I guess it's wrong 

You need python 3.6 anyways so just go to python website download 3.6 Windows installer it should set python path as well

**Comment by pmaji** [comment]
Yep, you have a versioning problem.

Tbh, I'd recommend just using one of the popular recent youtube tutorials to be sure you get it all right. One of them is here: https://www.youtube.com/watch?v=BcPIXq2hPtc

**Comment by shawn-j** [comment]
ok i installed 3.6 and it looks like it's working!  thanks for helping a noob out lol

**Comment by shawn-j** [comment]
great.. now i'm onto the next step, and getting another error.. should I start a new thread?  or just post it here..


D:\>pip install D:\_installers\crypto-whale-watching-app-master\requirements.txt

Invalid requirement: 'D:\_installers\crypto-whale-watching-app-master\requiremen
ts.txt'
It looks like a path. Does it exist ?

D:\>

**Comment by theimo1221** [comment]
@shawn-j I guess you are messing up the path....
Just open up that folder with all the files from here (requirements.txt app.py.....)
Click in the address bar and type cmd

This will open up command-line within correct directory. 
Then just type pip install -r requirements.txt 

Once it's done just type python app.py

**Comment by pmaji** [comment]
Closing because I assume given the lack of follow-up that this has been solved.

**Comment by shawn-j** [comment]
hi! sorry, the last response got buried in my email, trying it now

**Comment by theimo1221** [comment]
@shawn-j does it work?
